package codes

import (
	"fmt"
	"sort"
)

func init() {
	StatesCodes = make(map[string][]string)
	for _, ck := range CountriesCodes {
		for sk, _ := range States[ck] {
			StatesCodes[ck] = append(StatesCodes[ck], sk)
		}
		sort.Strings(StatesCodes[ck])
	}
}

var StatesCodes map[string][]string

var States = map[string]map[string]string{
	"AE": {
		"ABU": "Abu Dhabi",
		"AJM": "Ajman",
		"DUB": "Dubai",
		"FUJ": "Fujairah",
		"RAS": "Ras al-Khaimah",
		"SHA": "Sharjah",
		"UMM": "Umm al-Qawain",
	},
	"AR": {
		"00": "Capital Federal",
		"01": "Buenos Aires",
		"02": "Catamarca",
		"03": "Córdoba",
		"04": "Corrientes",
		"05": "Entre Rios",
		"06": "Jujuy",
		"07": "Mendoza",
		"08": "La Rioja",
		"09": "Salta",
		"10": "San Juan",
		"11": "San Luis",
		"12": "Santa Fé",
		"13": "Santiago del Estero",
		"14": "Tucumán",
		"16": "Chaco",
		"17": "Chubut",
		"18": "Formosa",
		"19": "Misiones",
		"20": "Neuquen",
		"21": "La Pampa",
		"22": "Rio Negro",
		"23": "Santa Cruz",
		"24": "Tierra de Fuego",
	},
	"AT": {
		"01": "Steiermark",
		"02": "Wien",
		"B":  "Burgenland",
		"K":  "Carinthia",
		"NÖ": "Lower Austria",
		"OÖ": "Upper Austria",
		"S":  "Salzburg",
		"ST": "Styria",
		"T":  "Tyrol",
		"V":  "Vorarlberg",
		"W":  "Vienna",
	},
	"AU": {
		"ACT": "Aust Capital Terr",
		"NSW": "New South Wales",
		"NT":  "Northern Territory",
		"QLD": "Queensland",
		"SA":  "South Australia",
		"TAS": "Tasmania",
		"VIC": "Victoria",
		"WA":  "Western Australia",
	},
	"AX": {
		"AX": "Aland Islands",
	},
	"BB": {
		"BB": "Barbados",
	},
	"BE": {
		"01": "Antwerp",
		"02": "DO NOT USE Brabant",
		"03": "Hainaut",
		"04": "Liege",
		"05": "Limburg",
		"06": "Luxembourg",
		"07": "Namur",
		"08": "Oost-Vlaanderen",
		"09": "West-Vlaanderen",
		"10": "DO NOT USE Anvers",
		"11": "Flandre - Occidental",
		"12": "Flandre - Orientale",
		"13": "Brabt Flmd",
		"14": "Brabt Waln",
		"15": "Brsl-Hfstd",
		"16": "Bruxl-Capt",
		"17": "Henegouwen",
		"18": "Limbourg",
		"19": "Leuttich",
		"20": "Luik",
		"21": "Luxemburg",
		"22": "Namen",
		"24": "Vlms-Brabnt",
		"25": "Wls-Brabnt",
	},
	"BG": {
		"01": "Burgas",
		"02": "Grad Sofiya",
		"03": "Khaskovo",
		"04": "Lovech",
		"05": "Montana",
		"06": "Plovdiv",
		"07": "Ruse",
		"08": "Sofiya",
		"09": "Varna",
	},
	"BQ": {
		"BO": "Bonaire",
		"BQ": "Bonaire",
		"SA": "Saba",
		"SE": "Statia",
	},
	"BR": {
		"AC": "Acre",
		"AL": "Alagoas",
		"AM": "Amazon",
		"AP": "Amapá",
		"BA": "Bahia",
		"CE": "Ceará",
		"DF": "Distrito Federal",
		"ES": "Espírito Santo",
		"GO": "Goiás",
		"MA": "Maranhão",
		"MG": "Minas Gerais",
		"MS": "Mato Grosso do Sul",
		"MT": "Mato Grosso",
		"PA": "Para",
		"PB": "Paraíba",
		"PE": "Pernambuco",
		"PI": "Piauí",
		"PR": "Paraná",
		"RJ": "Rio de Janeiro",
		"RN": "Rio Grande do Norte",
		"RO": "Rondônia",
		"RR": "Roraima",
		"RS": "Rio Grande do Sul",
		"SC": "Santa Catarina",
		"SE": "Sergipe",
		"SP": "São Paulo",
		"TO": "Tocatins",
	},
	"CA": {
		"AB": "Alberta",
		"BC": "British Columbia",
		"MB": "Manitoba",
		"NB": "New Brunswick",
		"NL": "Newfoundland",
		"NS": "Nova Scotia",
		"NT": "Northwest Territory",
		"NU": "Nunavut",
		"ON": "Ontario",
		"PE": "Prince Edward Island",
		"QC": "Quebec",
		"SK": "Saskatchewan",
		"YT": "Yukon Territory",
	},
	"CH": {
		"AG": "Aargau",
		"AI": "Inner-Rhoden",
		"AR": "Ausser-Rhoden",
		"BE": "Bern",
		"BL": "Basel Land",
		"BS": "Basel Stadt",
		"FR": "Fribourg",
		"GE": "Geneva",
		"GL": "Glarus",
		"GR": "Graubuenden",
		"JU": "Jura",
		"LU": "Lucerne",
		"NE": "Neuchatel",
		"NW": "Nidwalden",
		"OW": "Obwalden",
		"SG": "St. Gallen",
		"SH": "Schaffhausen",
		"SO": "Solothurn",
		"SZ": "Schwyz",
		"TG": "Thurgau",
		"TI": "Ticino",
		"UR": "Uri",
		"VD": "Vaud",
		"VS": "Valais",
		"ZG": "Zug",
		"ZH": "Zurich",
	},
	"CL": {
		"01": "I - Iquique",
		"02": "II - Antofagasta",
		"03": "III - Copiapo",
		"04": "IV - La Serena",
		"05": "V - Valparaiso",
		"06": "VI - Rancagua",
		"07": "VII - Talca",
		"08": "VIII - Concepción",
		"09": "IX - Temuco",
		"10": "X - Puerto Montt",
		"11": "XI - Coyhaique",
		"12": "XII - Punta Arenas",
		"13": "RM - Santiago",
		"14": "Arica",
		"15": "Biobío",
		"16": "Cachapoal",
		"17": "Capitán Prat Provinc",
		"18": "Cautín",
		"19": "Chacabuco",
		"20": "Chiloé",
		"21": "Colchagua",
		"22": "Cordillera",
		"23": "Curicó",
		"24": "Elqui",
		"25": "Limarí",
		"26": "Linares",
		"27": "Llanquihue",
		"28": "Magallanes",
		"29": "Maipo",
		"30": "Marga Marga",
		"31": "Melipilla",
		"32": "Ñuble",
		"33": "Osorno",
		"34": "Quillota",
		"35": "San Antonio",
		"36": "San Felipe",
		"37": "Talagante",
		"38": "Valdivia",
		"SA": "SANTIAGO",
	},
	"CN": {
		"010": "Beijing",
		"020": "Shanghai",
		"030": "Tianjin",
		"040": "NEI MONGUL (Out)",
		"050": "Shanxi",
		"060": "Hebei",
		"070": "Liaoning",
		"080": "Jilin",
		"090": "Heilongjiang",
		"100": "Jiangsu",
		"110": "Anhui",
		"11":  "Beijing",
		"120": "Shandong",
		"130": "Zhejiang",
		"140": "Jiangxi",
		"150": "Fujian",
		"160": "Hunan",
		"170": "Hubei",
		"180": "Henan",
		"190": "GUANGDON",
		"200": "Hainan",
		"210": "Guangxi",
		"220": "Guizhou",
		"230": "Sichuan",
		"240": "Yunnan",
		"250": "Shaanxi (OUT)",
		"260": "Gansu",
		"270": "Ningxia",
		"280": "Qinghai",
		"290": "Xinjiang",
		"300": "Xizang",
		"310": "Taiwan",
		"31":  "Shanghai",
		"320": "Chongqing",
		"330": "Heping",
		"340": "Neimenggu",
		"350": "HONG KONG",
		"360": "INNER MONGOLIA",
		"42":  "Hubei",
	},
	"CO": {
		"05": "ANTIOQUIA",
		"08": "ATLANTICO",
		"11": "BOGOTA",
		"13": "BOLIVAR",
		"15": "BOYACA",
		"17": "CALDAS",
		"18": "CAQUETA",
		"19": "CAUCA",
		"20": "CESAR",
		"23": "CORDOBA",
		"25": "CUNDINAMARCA",
		"27": "CHOCO",
		"41": "HUILA",
		"44": "LA GUAJIRA",
		"47": "MAGDALENA",
		"50": "META",
		"52": "NARIÑO",
		"54": "NORTE SANTANDER",
		"63": "QUINDIO",
		"66": "RISARALDA",
		"68": "SANTANDER",
		"70": "SUCRE",
		"73": "TOLIMA",
		"76": "VALLE DEL CAUCA",
		"81": "ARAUCA",
		"85": "CASANARE",
		"86": "PUTUMAYO",
		"88": "SAN ANDRES",
		"91": "AMAZONAS",
		"94": "GUAINIA",
		"95": "GUAVIARE",
		"97": "VAUPES",
		"99": "VICHADA",
	},
	"CW": {
		"CW": "Curacao",
	},
	"CZ": {
		"01": "Jihocesky",
		"02": "Jihomoravsky",
		"03": "Praha",
		"04": "Severocesky",
		"05": "Severomoravsky",
		"06": "Stredocesky",
		"07": "Vychodocesky",
		"08": "Zapadocesky",
		"P9": "Praha 9",
	},
	"DE": {
		"01": "Schleswig-Holstein",
		"02": "Hamburg",
		"03": "Niedersachsen",
		"04": "Bremen",
		"05": "Nordrhein-Westfalen",
		"06": "Hessen",
		"07": "Rheinland-Pfalz",
		"08": "Baden-Wurttemberg",
		"09": "Bayern",
		"10": "Saarland",
		"11": "Berlin",
		"12": "Brandenburg",
		"13": "Mecklenburg-Vorpomme",
		"14": "Sachsen",
		"15": "Sachsen-Anhalt",
		"16": "Thüringen",
		"BY": "Bayern",
	},
	"DK": {
		"001": "Copenhagen",
		"002": "Århus amt",
		"003": "Bornholm amt",
		"004": "Frederiksborg amt",
		"005": "Fyn amt",
		"006": "København amt",
		"007": "Nordjylland amt",
		"008": "Ribe amt",
		"009": "Ringkøbing amt",
		"010": "Roskilde amt",
		"011": "Sønderjylland amt",
		"012": "Storstrøm amt",
		"013": "Vejle amt",
		"014": "Vestsjælland amt",
		"015": "Viborg amt",
		"016": "Grønlands amt",
		"017": "Hovedstaden",
		"018": "Midtjylland",
		"019": "Nordjylland",
		"020": "Sjælland",
		"021": "Syddanmark",
	},
	"ES": {
		"01": "Alava",
		"02": "Albacete",
		"03": "Alicante",
		"04": "Almeria",
		"05": "Avila",
		"06": "Badajoz",
		"07": "Baleares",
		"08": "Barcelona",
		"09": "Burgos",
		"10": "Caceres",
		"11": "Cadiz",
		"12": "Castellon",
		"13": "Ciudad Real",
		"14": "Córdoba",
		"15": "La Coruña",
		"16": "Cuenca",
		"17": "Gerona",
		"18": "Granada",
		"19": "Guadalajara",
		"20": "Guipuzcoa",
		"21": "Huelva",
		"22": "Huesca",
		"23": "Jaen",
		"24": "Leon",
		"25": "Lerida",
		"26": "La Rioja",
		"27": "Lugo",
		"28": "Madrid",
		"29": "Malaga",
		"30": "Murcia",
		"31": "Navarra",
		"32": "Orense",
		"33": "Asturias",
		"34": "Palencia",
		"35": "Las Palmas",
		"36": "Pontevedra",
		"37": "Salamanca",
		"38": "Sta. Cruz Tenerife",
		"39": "Cantabria",
		"40": "Segovia",
		"41": "Sevilla",
		"42": "Soria",
		"43": "Tarragona",
		"44": "Teruel",
		"45": "Toledo",
		"46": "Valencia",
		"47": "Valladolid",
		"48": "Vizcaya",
		"49": "Zamora",
		"50": "Zaragoza",
	},
	"FI": {
		"001": "Ahvenanmaa",
		"002": "Etelä-Suomi",
		"003": "Itä-Suomi",
		"004": "Lappi",
		"005": "Länsi-Suomi",
		"006": "Oulu",
		"007": "Etelä-Karjala",
		"008": "Etelä-Pohjanmaa",
		"009": "Etelä-Savo",
		"010": "Hame",
		"011": "Itä-Uusimaa",
		"012": "Kainuu",
		"013": "Kanta-Häme",
		"014": "Keski-Pohjanmaa",
		"015": "Keski-Suomi",
		"016": "Kuopio",
		"017": "Kymenlaakso",
		"018": "Kymi",
		"019": "Mikkeli",
		"020": "Päijät-Häme",
		"021": "Pirkanmaa",
		"022": "Pohjanmaa",
		"023": "Pohjois-Karjala",
		"024": "Pohjois-Pohjanmaa",
		"025": "Pohjois-Savo",
		"026": "Satakunta",
		"027": "Turku Ja Pori",
		"028": "Uusimaa",
		"029": "Vaasa",
		"030": "Varsinais-Suomi",
		"HEL": "HELSINKI",
	},
	"FR": {
		"01":  "Ain",
		"02":  "Aisne",
		"03":  "Allier",
		"04":  "Alpes (Hte-Provence)",
		"05":  "Alpes (Hautes)",
		"06":  "Alpes-Maritimes",
		"07":  "Ardèche",
		"08":  "Ardennes",
		"09":  "Ariège",
		"100": "Corse",
		"10":  "Aube",
		"11":  "Aude",
		"12":  "Aveyron",
		"13":  "Bouches-du-Rhône",
		"14":  "Calvados",
		"15":  "Cantal",
		"16":  "Charente",
		"17":  "Charente-Maritime",
		"18":  "Cher",
		"19":  "Corrèze",
		"21":  "Côte-d&#39;Or",
		"22":  "Côtes-d&#39;Armor",
		"23":  "Creuse",
		"24":  "Dordogne",
		"25":  "Doubs",
		"26":  "Drôme",
		"27":  "Eure",
		"28":  "Eure-et-Loir",
		"29":  "Finistère",
		"2A":  "Corse-du-Sud",
		"2B":  "Corse-du-Nord",
		"30":  "Gard",
		"31":  "Garonne (Haute)",
		"32":  "Gers",
		"33":  "Gironde",
		"34":  "Hérault",
		"35":  "Ille-et-Vilaine",
		"36":  "Indre",
		"37":  "Indre-et-Loire",
		"38":  "Isère",
		"39":  "Jura",
		"40":  "Landes",
		"41":  "Loir-et-Cher",
		"42":  "Loire",
		"43":  "Loire (Haute)",
		"44":  "Loire-Atlantique",
		"45":  "Loiret",
		"46":  "Lot",
		"47":  "Lot-et-Garonne",
		"48":  "Lozère",
		"49":  "Maine-et-Loire",
		"50":  "Manche",
		"51":  "Marne",
		"52":  "Marne (Haute)",
		"53":  "Mayenne",
		"54":  "Meurthe-et-Moselle",
		"55":  "Meuse",
		"56":  "Morbihan",
		"57":  "Moselle",
		"58":  "Nièvre",
		"59":  "Nord",
		"60":  "Oise",
		"61":  "Orne",
		"62":  "Pas-de-Calais",
		"63":  "Puy-de-Dôme",
		"64":  "Pyrénées-Atlantiques",
		"65":  "Pyrénées (Hautes)",
		"66":  "Pyrénées-Orientales",
		"67":  "Bas-Rhin",
		"68":  "Haut-Rhin",
		"69":  "Rhône",
		"70":  "Saône (Haute)",
		"71":  "Saône-et-Loire",
		"72":  "Sarthe",
		"73":  "Savoie",
		"74":  "Savoie (Haute)",
		"75":  "Paris",
		"76":  "Seine-Maritime",
		"77":  "Seine-et-Marne",
		"78":  "Yvelines",
		"79":  "Sèvres (Deux)",
		"80":  "Somme",
		"81":  "Tarn",
		"82":  "Tarn-et-Garonne",
		"83":  "Var",
		"84":  "Vaucluse",
		"85":  "Vendée",
		"86":  "Vienne",
		"87":  "Vienne (Haute)",
		"88":  "Vosges",
		"89":  "Yonne",
		"90":  "Territ.-de-Belfort",
		"91":  "Essonne",
		"92":  "Hauts-de-Seine",
		"93":  "Seine-Saint-Denis",
		"94":  "Val-de-Marne",
		"95":  "Val-d&#39;Oise",
		"971": "Guadeloupe",
		"972": "Martinique",
		"973": "Guyane",
		"974": "Réunion",
		"975": "Saint-Pierre-et-Miq.",
		"976": "Wallis-et-Futuna",
		"97":  "D.O.M.-T.O.M.",
		"99":  "Hors-France",
	},
	"GB": {
		"01": "Isle of Man",
		"02": "Isles of Scilly",
		"03": "Middlesex",
		"04": "North Humberside",
		"05": "South Humberside",
		"06": "Manchester",
		"AB": "Aberdeenshire",
		"AG": "Argyll",
		"AM": "Armagh",
		"AN": "Angus",
		"AR": "Ards",
		"AT": "Antrim",
		"AV": "Avon",
		"AY": "Ayrshire",
		"B2": "Bracknell Forest",
		"BA": "Ballymena",
		"BB": "Blackburn",
		"BE": "Bedfordshire",
		"BF": "Banffshire",
		"BH": "Brighton &amp; Hove",
		"BK": "Berkshire",
		"BL": "Belfast",
		"BM": "Bournemouth",
		"BN": "Banbridge",
		"BO": "Borders",
		"BP": "Blackpool",
		"BR": "Bristol",
		"BS": "Bath&amp;NthEstSomerset",
		"BU": "Buckinghamshire",
		"BW": "Berwickshire",
		"BY": "Ballymoney",
		"C2": "Castlereagh",
		"CA": "Cambridgeshire",
		"CE": "Central",
		"CG": "Craigavon",
		"CH": "Cheshire",
		"CI": "Channel Islands",
		"CK": "Cookstown",
		"CL": "Clwyd",
		"CM": "Clackmannanshire",
		"CO": "Cornwall",
		"CR": "Carrickfergus",
		"CS": "Caithness",
		"CU": "Cumbria",
		"CV": "Cleveland",
		"CY": "County Tyrone",
		"D2": "Dungannon",
		"DB": "Derbyshire",
		"DF": "Dumfries a. Galloway",
		"DG": "County Fermanagh",
		"DL": "Darlington",
		"DN": "Down",
		"DO": "Dorset",
		"DS": "Dumfriesshire",
		"DT": "Dunbartonshire",
		"DU": "Durham",
		"DV": "Devon",
		"DY": "Dyfed",
		"EL": "East Lothian",
		"ER": "East Riding",
		"ES": "Essex",
		"FI": "Fife",
		"FM": "Fermanagh",
		"GL": "Gloucestershire",
		"GM": "Greater Manchester",
		"GR": "Grampian",
		"GS": "Sth. Gloucestershire",
		"GU": "Guernsey",
		"GW": "Gwent",
		"GY": "Gwynedd",
		"HA": "Hampshire",
		"HF": "Herefordshire",
		"HI": "Highland",
		"HL": "Halton",
		"HR": "Hartlepool",
		"HT": "Hertfordshire",
		"HU": "Humberside",
		"HW": "Hereford and Worcs.",
		"IA": "Isle Of Arran",
		"IB": "Isle Of Barra",
		"IC": "Isle Of Benbecula",
		"II": "Isle Of Islay",
		"IJ": "Isle Of Jura",
		"IK": "Isle Of Skye",
		"IL": "Isle Of Lewis",
		"IN": "Isle Of North Uist",
		"IS": "Isle Of South Uist",
		"IT": "Isle Of Bute",
		"IU": "Isle Of Mull",
		"IV": "Inverness Shire",
		"IW": "Isle of Wight",
		"JE": "Jersey",
		"KB": "Kirkcudbrightshire",
		"KC": "Kincardineshire",
		"KE": "Kent",
		"KH": "Kingston-upon-Hull",
		"KR": "Kinross Shire",
		"L2": "Lisburn",
		"LA": "Lancashire",
		"LC": "Leicester City",
		"LD": "Londonderry",
		"LE": "Leicestershire",
		"LI": "Lincolnshire",
		"LM": "Limavady",
		"LN": "London",
		"LO": "Greater London",
		"LR": "Larne",
		"LS": "Lisburn",
		"LT": "Lothian",
		"LU": "Luton",
		"MA": "Magherafelt",
		"MD": "Midlothian",
		"MG": "Mid Glamorgan",
		"MI": "Middlesbrough",
		"MK": "Milton Keynes",
		"MO": "Moyle",
		"MS": "Morayshire",
		"MY": "Merseyside",
		"N2": "Newtownabbey",
		"NA": "Nairnshire",
		"NB": "Newbury",
		"NC": "Nottingham City",
		"ND": "North Down",
		"NE": "NthEast Lincolnshire",
		"NH": "Northamptonshire",
		"NK": "Norfolk",
		"NL": "North Lincolnshire",
		"NM": "Newry and Mourne",
		"NS": "North Somerset",
		"NT": "Nottinghamshire",
		"NU": "Northumberland",
		"OM": "Omagh",
		"OR": "Orkney",
		"OX": "Oxfordshire",
		"PB": "Peterborough",
		"PL": "Poole",
		"PM": "Portsmouth",
		"PO": "Powys",
		"PS": "Peeblesshire",
		"PT": "Perthshire",
		"PY": "Plymouth",
		"RD": "Redcar and Cleveland",
		"RE": "Reading",
		"RF": "Renfrewshire",
		"RM": "Rochester up. Medway",
		"RS": "Ross Shire",
		"RU": "Rutland",
		"RX": "Roxburghshire",
		"S2": "Stockton-on-Tees",
		"SA": "Sutherland",
		"SC": "Strathclyde",
		"SD": "Southend",
		"SE": "East Sussex",
		"SG": "South Glamorgan",
		"SH": "Shropshire",
		"SI": "Shetland Islands",
		"SK": "Suffolk",
		"SL": "Shetland",
		"SN": "Stirlingshire",
		"SO": "Somerset",
		"SP": "Southampton",
		"SR": "Strabane",
		"SS": "Selkirkshire",
		"ST": "Staffordshire",
		"SU": "Slough",
		"SW": "West Sussex",
		"SX": "Sussex",
		"SY": "Surrey",
		"TA": "Tayside",
		"TD": "Thamesdown",
		"TH": "Thurrock",
		"TO": "Torbay",
		"TW": "Tyne and Wear",
		"WA": "Warwickshire",
		"WD": "Windsor &amp; Maidenhead",
		"WE": "Wales",
		"WG": "West Glamorgan",
		"WI": "Wiltshire",
		"WL": "Western Isles",
		"WM": "West Midlands",
		"WN": "West Lothian",
		"WO": "Worcestershire",
		"WR": "Wrekin",
		"WS": "Wigtownshire",
		"WT": "Warrington",
		"YK": "York",
		"YN": "North Yorkshire",
		"YS": "South Yorkshire",
		"YW": "West Yorkshire",
	},
	"GG": {
		"GG": "Guernsey",
	},
	"GR": {
		"01": "Aitolia kai Akarnan.",
		"02": "Akhaia",
		"03": "Argolis",
		"04": "Arkadhia",
		"05": "Arta",
		"06": "Attiki",
		"07": "Dhodhekanisos",
		"08": "Dhrama",
		"09": "Evritania",
		"10": "Evros",
		"11": "Evvoia",
		"12": "Florina",
		"13": "Fokis",
		"14": "Fthiotis",
		"15": "Grevena",
		"16": "Ilia",
		"17": "Imathia",
		"18": "Ioannina",
		"19": "Iraklion",
		"20": "Kardhitsa",
		"21": "Kastoria",
		"22": "Kavala",
		"23": "Kefallinia",
		"24": "Kerkira",
		"25": "Khalkidhiki",
		"26": "Khania",
		"27": "Khios",
		"28": "Kikladhes",
		"29": "Kilkis",
		"30": "Korinthia",
		"31": "Kozani",
		"32": "Lakonia",
		"33": "Larisa",
		"34": "Lasithi",
		"35": "Lesvos",
		"36": "Levkas",
		"37": "Magnisia",
		"38": "Messinia",
		"39": "Pella",
		"40": "Pieria",
		"41": "Piraievs",
		"42": "Preveza",
		"43": "Rethimni",
		"44": "Rodhopi",
		"45": "Samos",
		"46": "Serrai",
		"47": "Thesprotia",
		"48": "Thessaloniki",
		"49": "Trikala",
		"50": "Voiotia",
		"51": "Xanthi",
		"52": "Zakinthos",
		"AT": "Athens",
	},
	"HK": {
		"01": "Outlying Islands",
		"HK": "Hong Kong Island",
		"KL": "Kowloon",
		"NT": "New Territories",
	},
	"HR": {
		"01": "Bjelovar-Bilogora",
		"02": "Stadt Zagreb",
		"03": "Dubrovnik-Neretva",
		"04": "Istra",
		"05": "Karlovac",
		"06": "Koprivnica-Krizevci",
		"07": "Lika-Senj",
		"08": "Medimurje",
		"09": "Osijek-Baranja",
		"10": "Pozega-Slavonija",
		"11": "Primorje-Gorski Kot.",
		"12": "Sibenik",
		"13": "Sisak-Moslavina",
		"14": "Slavonski",
		"15": "Brod-Posavina",
		"16": "Split-Dalmatia",
		"17": "Varazdin",
		"18": "Virovitica-Podravina",
		"19": "Vukovar-Srijem",
		"20": "Zadar-Knin",
		"21": "Zagreb",
	},
	"HU": {
		"01": "Bacs-Kiskun",
		"02": "Baranya",
		"03": "Bekes",
		"04": "Bekescsaba",
		"05": "Borsod-Abauj-Zemplen",
		"06": "Budapest",
		"07": "Csongrad",
		"08": "Debrecen",
		"09": "Dunaujvaros",
		"10": "Eger",
		"11": "Fejer",
		"12": "Gyor",
		"13": "Gyor-Moson-Sopron",
		"14": "Hajdu-Bihar",
		"15": "Heves",
		"16": "Hodmezovasarhely",
		"17": "Jasz-Nagykun-Szolnok",
		"18": "Kaposvar",
		"19": "Kecskemet",
		"20": "Komarom-Esztergom",
		"21": "Miskolc",
		"22": "Nagykanizsa",
		"23": "Nograd",
		"24": "Nyiregyhaza",
		"25": "Pecs",
		"26": "Pest",
		"27": "Somogy",
		"28": "Sopron",
		"29": "Szabolcs-Szat.-Bereg",
		"30": "Szeged",
		"31": "Szekesfehervar",
		"32": "Szolnok",
		"33": "Szombathely",
		"34": "Tatabanya",
		"35": "Tolna",
		"36": "Vas",
		"37": "Veszprem",
		"38": "Zala",
		"39": "Zalaegerszeg",
	},
	"ID": {
		"01": "DKI Jakarta Jakarta",
		"02": "Jawa Barat West Java",
		"03": "Jawa Tengah Central",
		"04": "Jawa Timur East Java",
		"05": "DI Yogyakarta Yogyak",
		"06": "DI Aceh Aceh",
		"07": "Sumatera Utara North",
		"08": "Sumatera Barat West",
		"09": "Riau Riau",
		"10": "Jambi Jambi",
		"11": "Sumatera Selatan Sou",
		"12": "Bengkulu Bengkulu",
		"13": "Lampung Lampung",
		"14": "Kalimantan Selatan S",
		"15": "Kalimantan Barat Wes",
		"16": "Kalimantan Tengah Ce",
		"17": "Kalimantan Timur Eas",
		"18": "Sulawesi Selatan Sou",
		"19": "Sulawesi Tenggara So",
		"20": "Sulawesi Tengah Cent",
		"21": "Sulawesi Utara North",
		"22": "Bali Bali",
		"23": "Nusa Tenggara Barat",
		"24": "Nusa Tenggara Timur",
		"25": "Maluku Maluku",
		"26": "Irian Jaya Irian Jay",
		"27": "Timor Timur East Tim",
	},
	"IE": {
		"AM": "Armagh",
		"AN": "Antrim",
		"AR": "Arklow",
		"CH": "Chairrai",
		"CK": "Cork",
		"CL": "Clare",
		"CV": "Cavan",
		"CW": "Carlow",
		"DB": "Dublin",
		"DG": "Donegal",
		"DW": "Down",
		"DY": "Derry",
		"FM": "Fermanagh",
		"GA": "Gaillimhe",
		"GW": "Galway",
		"KD": "Kildare",
		"KK": "Kilkenny",
		"KY": "Kerry",
		"LF": "Longford",
		"LI": "Limerick",
		"LM": "Leitrim",
		"LS": "Laois",
		"LT": "Louth",
		"MH": "Monaghan",
		"MT": "Meath",
		"MY": "Mayo",
		"NE": "Neath",
		"OF": "Offaly",
		"PH": "Phortláige",
		"RC": "Rosscommon",
		"SG": "Sligo",
		"TP": "Tipperary",
		"TY": "Tyrone",
		"WF": "Waterford",
		"WK": "Wicklow",
		"WM": "Westmeath",
		"WX": "Wexford",
	},
	"IL": {
		"01": "Central",
		"02": "Haifa",
		"03": "Jerusalem",
		"04": "Northern",
		"05": "Southern",
		"06": "Tel Aviv",
		"IL": "Israel",
	},
	"IM": {
		"IM": "Isle of Man",
	},
	"IN": {
		"01":  "Andhra Pradesh",
		"02":  "Arunachal Pradesh",
		"03":  "Assam",
		"04":  "Bihar",
		"05":  "Goa",
		"06":  "Gujarat",
		"07":  "Haryana",
		"08":  "Himachal Pradesh",
		"09":  "Jammu and Kashmir",
		"10":  "Karnataka",
		"11":  "Kerala",
		"12":  "Madhya Pradesh",
		"13":  "Maharashtra",
		"14":  "Manipur",
		"15":  "Meghalaya",
		"16":  "Mizoram",
		"17":  "Nagaland",
		"18":  "Orissa",
		"19":  "Punjab",
		"20":  "Rajasthan",
		"21":  "Sikkim",
		"22":  "Tamil Nadu",
		"23":  "Tripura",
		"24":  "Uttar Pradesh",
		"25":  "West Bengal",
		"26":  "Andaman and Nico.In.",
		"27":  "Chandigarh",
		"28":  "Dadra and Nagar Hav.",
		"29":  "Daman and Diu",
		"30":  "Delhi",
		"31":  "Lakshadweep Islands",
		"32":  "Puducherry",
		"33":  "Chattisgarh",
		"35":  "Jharkand",
		"37":  "Mahrashtra (OUT)",
		"38":  "Delhi (OUT)",
		"39":  "Utranchal",
		"40":  "UP (OUT)",
		"41":  "Uttarakhand",
		"BKP": "Bavadhan Khurd, Pune",
		"IN":  "India",
	},
	"IT": {
		"AG": "Agriento",
		"AL": "Alessandria",
		"AN": "Ancona",
		"AO": "Aosta",
		"AP": "Ascoli Piceno",
		"AQ": "L&#39;Aquila",
		"AR": "Arezzo",
		"AT": "Asti",
		"AV": "Avellino",
		"BA": "Bari",
		"BG": "Bergamo",
		"BI": "Biella",
		"BL": "Belluno",
		"BN": "Benevento",
		"BO": "Bologna",
		"BR": "Brindisi",
		"BS": "Brescia",
		"BZ": "Bolzano",
		"CA": "Cagliari",
		"CB": "Campobasso",
		"CE": "Caserta",
		"CH": "Chieti",
		"CL": "Caltanisetta",
		"CN": "Cuneo",
		"CO": "Como",
		"CR": "Cremona",
		"CS": "Cosenza",
		"CT": "Catania",
		"CZ": "Catanzaro",
		"EN": "Enna",
		"FE": "Ferrara",
		"FG": "Foggia",
		"FI": "Florence",
		"FO": "Forlì",
		"FR": "Frosinone",
		"GE": "Genova",
		"GO": "Gorizia",
		"GR": "Grosseto",
		"IM": "Imperia",
		"IS": "Isernia",
		"KR": "Crotone",
		"LC": "Lecco",
		"LE": "Lecce",
		"LI": "Livorno",
		"LO": "Lodi",
		"LT": "Latina",
		"LU": "Lucca",
		"MC": "Macerata",
		"ME": "Messina",
		"MI": "Milan",
		"MN": "Mantova",
		"MO": "Modena",
		"MS": "Massa Carrara",
		"MT": "Matera",
		"NA": "Naples",
		"NO": "Novara",
		"NU": "Nuoro",
		"OR": "Oristano",
		"PA": "Palermo",
		"PC": "Piacenza",
		"PD": "Padova",
		"PE": "Pescara",
		"PG": "Perugia",
		"PI": "Pisa",
		"PN": "Pordenone",
		"PO": "Prato",
		"PR": "Parma",
		"PS": "Pesaro",
		"PT": "Pistoia",
		"PV": "Pavia",
		"PZ": "Potenza",
		"RA": "Ravenna",
		"RC": "Reggio Calabria",
		"RE": "Reggio Emilia",
		"RG": "Ragusa",
		"RI": "Rieti",
		"RM": "Rome",
		"RN": "Rimini",
		"RO": "Rovigo",
		"SA": "Salerno",
		"SI": "Siena",
		"SO": "Sondrio",
		"SP": "La Spezia",
		"SR": "Siracusa",
		"SS": "Sassari",
		"SV": "Savona",
		"TA": "Taranto",
		"TE": "Teramo",
		"TN": "Trento",
		"TO": "Turin",
		"TP": "Trapani",
		"TR": "Terni",
		"TS": "Trieste",
		"TV": "Treviso",
		"UD": "Udine",
		"VA": "Varese",
		"VB": "Verbania",
		"VC": "Vercelli",
		"VE": "Venice",
		"VI": "Vicenza",
		"VR": "Verona",
		"VT": "Viterbo",
		"VV": "Vibo Valentia",
	},
	"JE": {
		"JE": "Jersey",
	},
	"JP": {
		"01": "Hokkaido",
		"02": "Aomori-ken",
		"03": "Iwate-ken",
		"04": "Miyagi-ken",
		"05": "Akita-ken",
		"06": "Yamagata-ken",
		"07": "Fukushima-ken",
		"08": "Ibaraki-ken",
		"09": "Tochigi-ken",
		"10": "Gunma-ken",
		"11": "Saitama-ken",
		"12": "Chiba-ken",
		"13": "Tokyo-to",
		"14": "Kanagawa-ken",
		"15": "Niigata-ken",
		"16": "Toyama-ken",
		"17": "Ishikawa-ken",
		"18": "Fukui-ken",
		"19": "Yamanashi-ken",
		"20": "Nagano-ken",
		"21": "Gifu-ken",
		"22": "Shizuoka-ken",
		"23": "Aichi-ken",
		"24": "Mie-ken",
		"25": "Shiga-ken",
		"26": "Kyoto-fu",
		"27": "Osaka-fu",
		"28": "Hyogo-ken",
		"29": "Nara-ken",
		"30": "Wakayama-ken",
		"31": "Tottori-ken",
		"32": "Shimane-ken",
		"33": "Okayama-ken",
		"34": "Hiroshima-ken",
		"35": "Yamaguchi-ken",
		"36": "Tokushima-ken",
		"37": "Kagawa-ken",
		"38": "Ehime-ken",
		"39": "Kochi-ken",
		"40": "Fukuoka-ken",
		"41": "Saga-ken",
		"42": "Nagasaki-ken",
		"43": "Kumamoto-ken",
		"44": "Oita-ken",
		"45": "Miyazaki-ken",
		"46": "Kagoshima-ken",
		"47": "Okinawa-ken",
	},
	"KR": {
		"01":  "Cheju-do",
		"02":  "Cholla-bukto",
		"03":  "Cholla-namdo",
		"04":  "Ch´ungch´ong-bukto",
		"05":  "Ch´ungch´ong-namdo",
		"06":  "Inch´on-jikhalsi",
		"07":  "Kangwon-do",
		"08":  "Kwangju-jikhalsi",
		"09":  "Kyonggi-do",
		"10":  "Kyongsang-bukto",
		"11":  "Kyongsang-namdo",
		"12":  "Pusan-jikhalsi",
		"13":  "Soul-t´ukpyolsi",
		"14":  "Taegu-jikhalsi",
		"15":  "Taejon-jikhalsi",
		"16":  "Ulsan",
		"SEO": "Seoul, S. Korea",
	},
	"KY": {
		"01":  "Cayman Brac",
		"02":  "Grand Cayman",
		"03":  "Little Cayman",
		"BWI": "British West Indies",
	},
	"KZ": {
		"00": "Almatynskaia",
		"01": "Kostanaiskaia",
		"02": "Severo-Kazakhstansk",
		"03": "Pavlodarskaia",
		"04": "Akmolinskaia",
		"05": "Aktubinskaia",
		"06": "Atyrauskaia",
		"07": "Zapadno-Kazakhst",
		"08": "Mangystayskaia",
		"09": "Karagandinskaia",
		"10": "Vostochno-Kazakhstan",
		"11": "Gambilskaia",
		"12": "Kyzilordinskaia",
	},
	"LK": {
		"CO": "Colombo",
	},
	"LU": {
		"LU": "Luxembourg",
	},
	"LV": {
		"RG": " ",
	},
	"MO": {
		"01": "Coloane",
		"02": "Macao",
		"03": "Taipa",
	},
	"MX": {
		"AGS": "Aguascalientes",
		"BC":  "Baja California",
		"BCS": "Baja California S",
		"CHI": "Chihuahua",
		"CHS": "Chiapas",
		"CMP": "Campeche",
		"COA": "Coahuila",
		"COL": "Colima",
		"DF":  "Distrito Federal",
		"DGO": "Durango",
		"GRO": "Guerrero",
		"GTO": "Guanajuato",
		"HGO": "Hidalgo",
		"JAL": "Jalisco",
		"MCH": "Michoacán",
		"MEX": "Estado de México",
		"MOR": "Morelos",
		"NAY": "Nayarit",
		"NL":  "Nuevo Léon",
		"OAX": "Oaxaca",
		"PUE": "Puebla",
		"QRO": "Querétaro",
		"QR":  "Quintana Roo",
		"SIN": "Sinaloa",
		"SLP": "San Luis Potosí",
		"SON": "Sonora",
		"TAB": "Tabasco",
		"TLX": "Tlaxcala",
		"TMS": "Tamaulipas",
		"VER": "Veracruz",
		"YUC": "Yucatán",
		"ZAC": "Zacatecas",
	},
	"MY": {
		"JOH": "Johor",
		"KED": "Kedah",
		"KEL": "Kelantan",
		"KUL": "Kuala Lumpur",
		"LAB": "Labuan",
		"MEL": "Melaka",
		"PAH": "Pahang",
		"PEL": "Perlis",
		"PER": "Perak",
		"PIN": "Pulau Pinang",
		"PUT": "Putrajava",
		"SAB": "Sabah",
		"SAR": "Sarawak",
		"SEL": "Selangor",
		"SER": "Negeri Sembilan",
		"TRE": "Terengganu",
	},
	"NL": {
		"01": "Drenthe",
		"02": "Flevoland",
		"03": "Friesland",
		"04": "Gelderland",
		"05": "Groningen",
		"06": "Limburg",
		"07": "Noord-Brabant",
		"08": "Noord-Holland",
		"09": "Overijssel",
		"10": "Utrecht",
		"11": "Zeeland",
		"12": "Zuid-Holland",
		"NL": "Netherlands",
	},
	"NO": {
		"01": "Østfold Fylke",
		"02": "Akershus Fylke",
		"03": "Oslo",
		"04": "Hedmark Fylke",
		"05": "Oppland Fylke",
		"06": "Buskerud Fylke",
		"07": "Vestfold Fylke",
		"08": "Telemark Fylke",
		"09": "Aust-Agder Fylke",
		"10": "Vest-Agder Fylke",
		"11": "Rogaland Fylke",
		"12": "Hordaland Fylke",
		"14": "Sogn og Fjordane F.",
		"15": "Møre og Romsdal F.",
		"16": "Sør-Trøndelag Fylke",
		"17": "Nord-Trøndelag Fylke",
		"18": "Nordland Fylke",
		"19": "Troms Fylke",
		"20": "Finnmark Fylke",
	},
	"NZ": {
		"AUC": "Auckland",
		"BOP": "Bay of Plenty",
		"CAN": "Canterbury",
		"HAB": "Hawke´s Bay",
		"MAN": "Manawatu-Wanganui",
		"NTL": "Northland",
		"OTA": "Otago",
		"STL": "Southland",
		"TAR": "Taranaki",
		"WAI": "Waikato",
		"WEC": "West Coast",
		"WLG": "Wellington",
	},
	"PE": {
		"01": "Tumbes",
		"02": "Piura",
		"03": "Lambayeque",
		"04": "La Libertad",
		"05": "Ancash",
		"06": "Lima y Callao",
		"07": "Ica",
		"08": "Arequipa",
		"09": "Moquegua",
		"10": "Tacna",
		"11": "Amazon",
		"12": "Cajamarca",
		"13": "San Martín",
		"14": "Huánuco",
		"15": "Pasco",
		"16": "Junín",
		"17": "Huancavelica",
		"18": "Ayacucho",
		"19": "Apurimac",
		"20": "Cuzco",
		"21": "Puno",
		"22": "Loreto",
		"23": "Ucayali",
		"24": "Madre de Díos",
		"25": "Callao",
	},
	"PH": {
		"01": "Ilocos",
		"02": "Cagayan Valley",
		"03": "Central Luzon",
		"04": "South Luzon",
		"05": "Bicol",
		"06": "West Visayas",
		"07": "Central Visayas",
		"08": "Eastern Visayas",
		"09": "Western Mindanao",
		"10": "Northern Mindanao",
		"11": "Cntrl Mindanao",
		"12": "South Mindanao",
	},
	"PL": {
		"01": "Biala Podlaska",
		"02": "Bialystok",
		"03": "Bielsko Biala",
		"04": "Bydgoszcz",
		"05": "Chelm",
		"06": "Ciechanow",
		"07": "Czestochowa",
		"08": "Elblag",
		"09": "Gdansk",
		"10": "Gorzow",
		"11": "Jelenia Gora",
		"12": "Kalisz",
		"13": "Katowice",
		"14": "Kielce",
		"15": "Konin",
		"16": "Koszalin",
		"17": "Krakow",
		"18": "Krosno",
		"19": "Legnica",
		"20": "Leszno",
		"21": "Lodz",
		"22": "Lomza",
		"23": "Lublin",
		"24": "Nowy Sacz",
		"25": "Olsztyn",
		"26": "Opole",
		"27": "Ostroleka",
		"28": "Pila",
		"29": "Piotrkow",
		"30": "Plock",
		"31": "Poznan",
		"32": "Przemysl",
		"33": "Radom",
		"34": "Rzeszow",
		"35": "Siedlce",
		"36": "Sieradz",
		"37": "Skierniewice",
		"38": "Slupsk",
		"39": "Suwalki",
		"40": "Szczecin",
		"41": "Tarnobrzeg",
		"42": "Tarnow",
		"43": "Torun",
		"44": "Walbrzych",
		"45": "Warszawa",
		"46": "Wloclawek",
		"47": "Wroclaw",
		"48": "Zamosc",
		"49": "Zielona Gora",
		"50": "Dolnoslaskie",
		"51": "Kujawsko-Pomorskie",
		"52": "Lódzkie",
		"53": "Lubelskie",
		"54": "Lubuskie",
		"55": "Malopolskie",
		"56": "Mazowieckie",
		"57": "Opolskie",
		"58": "Podkarpackie",
		"59": "Podlaskie",
		"60": "Pomorskie",
		"61": "Slaskie",
		"62": "Swietokrzyskie",
		"63": "Warminsko-Mazurskie",
		"64": "Wielkopolskie",
		"65": "Zachodniopomorskie",
	},
	"PS": {
		"10":  "OPT",
		"BTH": "Bethlehem",
		"DEB": "DirElBalah",
		"GZA": "Gaza",
		"HBN": "Hebron",
		"JEM": "Jerusalem",
		"JEN": "Jenin",
		"JRH": "Jericho",
		"KYS": "Khan Yunis",
		"NBS": "Nablus",
		"NGZ": "North Gaza",
		"PS":  "Palestine,State",
		"QQA": "Qalqilya",
		"RBH": "Ramallah",
		"RFH": "Rafah",
		"SLT": "Salfit",
		"TBS": "Tubas",
		"TKM": "Tulkarm",
	},
	"PT": {
		"10": "Minho-Lima",
		"11": "Cávado",
		"12": "Ave",
		"13": "Grande Porto",
		"14": "Tâmega",
		"15": "Entre Douro e Vouga",
		"16": "Douro",
		"17": "Alto Trás-os-Montes",
		"20": "Baixo Vouga",
		"21": "Baixo Mondego",
		"22": "Pinhal Litoral",
		"23": "Pinhal Interior N.",
		"24": "Pinhal Interior Sul",
		"25": "Dão-Lafoes",
		"26": "Serra da Estrela",
		"27": "Beira Interior Norte",
		"28": "Beira Interior Sul",
		"29": "Cova da Beira",
		"30": "Oeste",
		"31": "Grande Lisboa",
		"32": "Península de Setúbal",
		"33": "Médio Tejo",
		"34": "Lezíria do Tejo",
		"40": "Alentejo Litoral",
		"41": "Alto Alentejo",
		"42": "Alentejo Central",
		"43": "Baixo Alentejo",
		"50": "Algarve",
		"60": "Reg. Aut. dos Açores",
		"70": "Reg. Aut. da Madeira",
	},
	"PY": {
		"01": "Alto Parana",
		"02": "Amambay",
		"03": "Boqueron",
		"04": "Caaguazu",
		"05": "Caazapa",
		"06": "Central",
		"07": "Concepcion",
		"08": "Cordillera",
		"09": "Guaira",
		"10": "Itapua",
		"11": "Misiones",
		"12": "Neembucu",
		"13": "Olimpo",
		"14": "Paraguari",
		"15": "Presidente Hayes",
		"16": "San Pedro",
	},
	"RO": {
		"01": "Alba",
		"02": "Arad",
		"03": "Arges",
		"04": "Bacau",
		"05": "Bihor",
		"06": "Bistrita-Nasaud",
		"07": "Botosani",
		"08": "Braila",
		"09": "Brasov",
		"10": "Bucuresti",
		"11": "Buzau",
		"12": "Calarasi",
		"13": "Caras-Severin",
		"14": "Cluj",
		"15": "Constanta",
		"16": "Covasna",
		"17": "Dimbovita",
		"18": "Dolj",
		"19": "Galati",
		"20": "Gorj",
		"21": "Giurgiu",
		"22": "Harghita",
		"23": "Hunedoara",
		"24": "Ialomita",
		"25": "Iasi",
		"26": "Maramures",
		"27": "Mehedinti",
		"28": "Mures",
		"29": "Neamt",
		"30": "Olt",
		"31": "Prahova",
		"32": "Salaj",
		"33": "Satu Mare",
		"34": "Sibiu",
		"35": "Suceava",
		"36": "Teleorman",
		"37": "Timis",
		"38": "Tulcea",
		"39": "Vaslui",
		"40": "Vilcea",
		"41": "Vrancea",
	},
	"RU": {
		"01": "Adigeja Republic",
		"02": "Highlands-Altay Rep.",
		"03": "Republ.of Bashkortos",
		"04": "Buryat Republic",
		"05": "Dagestan Republic",
		"06": "Ingushetija Republic",
		"07": "Kabardino-Balkar.Rep",
		"08": "Kalmyk Republic",
		"09": "Karach.-Cherkessk Re",
		"10": "Karelian Republic",
		"11": "Komi Republic",
		"12": "Marijskaya Republic",
		"13": "Mordovian Republic",
		"14": "Yakutiya-Saha Rrepub",
		"15": "North-Osetiya Republ",
		"16": "Tatarstan Republic",
		"17": "Tuva Republic",
		"18": "The Udmurt Republic",
		"19": "Chakassky Republic",
		"20": "Chechenskaya Republ.",
		"21": "Chuvash Republic",
		"22": "Altay Territory",
		"23": "Krasnodar Territory",
		"24": "Krasnoyarsk Territor",
		"25": "Primorye Territory",
		"26": "Stavropol Territory",
		"27": "Khabarovsk Territory",
		"28": "The Amur Area",
		"29": "The Arkhangelsk Area",
		"30": "The Astrakhan Area",
		"31": "The Belgorod Area",
		"32": "The Bryansk Area",
		"33": "The Vladimir Area",
		"34": "The Volgograd Area",
		"35": "The Vologda Area",
		"36": "The Voronezh Area",
		"37": "The Ivanovo Area",
		"38": "The Irkutsk Area",
		"39": "The Kaliningrad Area",
		"40": "The Kaluga Area",
		"41": "The Kamchatka Area",
		"42": "The Kemerovo Area",
		"43": "The Kirov Area",
		"44": "The Kostroma Area",
		"45": "The Kurgan Area",
		"46": "The Kursk Area",
		"47": "The Leningrad Area",
		"48": "The Lipetsk Area",
		"49": "The Magadan Area",
		"50": "The Moscow Area",
		"51": "The Murmansk Area",
		"52": "The Nizhniy Novgorod",
		"53": "The Novgorod Area",
		"54": "The Novosibirsk Area",
		"55": "The Omsk Area",
		"56": "The Orenburg Area",
		"57": "The Oryol Area",
		"58": "The Penza Area",
		"59": "The Perm Area",
		"60": "The Pskov Area",
		"61": "The Rostov Area",
		"62": "The Ryazan Area",
		"63": "The Samara Area",
		"64": "The Saratov Area",
		"65": "The Sakhalin Area",
		"66": "The Sverdlovsk Area",
		"67": "The Smolensk Area",
		"68": "The Tambov Area",
		"69": "The Tver Area",
		"70": "The Tomsk Area",
		"71": "The Tula Area",
		"72": "The Tyumen Area",
		"73": "The Ulyanovsk Area",
		"74": "The Chelyabinsk Area",
		"75": "The Chita Area",
		"76": "The Yaroslavl Area",
		"77": "c.Moscow",
		"78": "c.St-Peterburg",
		"79": "The Jewish Auton.are",
		"80": "Aginsk Buryat Aut.di",
		"81": "Komy Permjats.Aut.di",
		"82": "Korjacs Auton.distri",
		"83": "Nenekchky Auton.dist",
		"84": "The Taymir Auton.dis",
		"85": "Ust-Ordinsky Buryat",
		"86": "Chanti-Mansyjsky Aut",
		"87": "Chukotka Auton. dist",
		"88": "Evensky Auton.distri",
		"89": "Jamalo-Nenekchky Aut",
	},
	"SE": {
		"001": "Blekinge Län",
		"002": "Dalarnas Län",
		"003": "Gotlands Län",
		"004": "Gävleborgs Län",
		"005": "Hallands Län",
		"006": "Jämtlands Län",
		"007": "Jönköpings Län",
		"008": "Kalmar Län",
		"009": "Kronobergs Län",
		"010": "Norrbottens Län",
		"011": "Skåne Län",
		"012": "Stockholms Län",
		"013": "Södermanlands Län",
		"014": "Uppsala Län",
		"015": "Värmlands Län",
		"016": "Västerbottens Län",
		"017": "Västernorrlands Län",
		"018": "Västmanlands Län",
		"019": "Västra Götalands Län",
		"020": "Örebro Län",
		"021": "Östergötlands Län",
		"022": "Alvsborgs Lan",
		"023": "Kopparbergs Lan",
		"024": "Malmohus Lan",
		"025": "Skaraborgs Lan",
		"SE":  "Stockholm",
	},
	"SG": {
		"SG": "Singapore",
	},
	"SI": {
		"01": "Ajdovscina",
		"02": "Brezice",
		"03": "Celje",
		"04": "Cerknica",
		"05": "Crnomelj",
		"06": "Dravograd",
		"07": "Gornja Radgona",
		"08": "Grosuplje",
		"09": "Hrastnik Lasko",
		"10": "Idrija",
		"11": "Ilirska Bistrica",
		"12": "Izola",
		"13": "Jesenice",
		"14": "Kamnik",
		"15": "Kocevje",
		"16": "Koper",
		"17": "Kranj",
		"18": "Krsko",
		"19": "Lenart",
		"20": "Lendava",
		"21": "Litija",
		"22": "Ljubljana-Bezigrad",
		"23": "Ljubljana-Center",
		"24": "Ljubljana-Moste-Polj",
		"25": "Ljubljana-Siska",
		"26": "Ljubljana-Vic-Rudnik",
		"27": "Ljutomer",
		"28": "Logatec",
		"29": "Maribor",
		"30": "Metlika",
		"31": "Mozirje",
		"32": "Murska Sobota",
		"33": "Nova Gorica",
		"34": "Novo Mesto",
		"35": "Ormoz",
		"36": "Pesnica",
		"37": "Piran",
		"38": "Postojna",
		"39": "Ptuj",
		"40": "Radlje Ob Dravi",
		"41": "Radovljica",
		"42": "Ravne Na Koroskem",
		"43": "Ribnica",
		"44": "Ruse",
		"45": "Sentjur Pri Celju",
		"46": "Sevnica",
		"47": "Sezana",
		"48": "Skofja Loka",
		"49": "Slovenj Gradec",
		"50": "Slovenska Bistrica",
		"51": "Slovenske Konjice",
		"52": "Smarje Pri Jelsah",
		"53": "Tolmin",
		"54": "Trbovlje",
		"55": "Trebnje",
		"56": "Trzic",
		"57": "Velenje",
		"58": "Vrhnika",
		"59": "Zagorje Ob Savi",
		"60": "Zalec",
	},
	"SK": {
		"01": "Bratislava",
		"02": "Zapadoslovensky",
		"03": "Stredoslovensky",
		"04": "Vychodoslovensky",
	},
	"SX": {
		"SX": "Sint Maarten",
	},
	"TH": {
		"01": "Amnat Charoen",
		"02": "Ang Thong",
		"03": "Buriram",
		"04": "Chachoengsao",
		"05": "Chai Nat",
		"06": "Chaiyaphum",
		"07": "Chanthaburi",
		"08": "Chiang Mai",
		"09": "Chiang Rai",
		"10": "Chon Buri",
		"11": "Chumphon",
		"12": "Kalasin",
		"13": "Kamphaeng Phet",
		"14": "Kanchanaburi",
		"15": "Khon Kaen",
		"16": "Krabi",
		"17": "Krung Thep",
		"18": "Mahanakhon",
		"19": "Lampang",
		"20": "Lamphun",
		"21": "Loei",
		"22": "Lop Buri",
		"23": "Mae Hong Son",
		"24": "Maha Sarakham",
		"25": "Mukdahan",
		"26": "Nakhon Nayok",
		"27": "Nakhon Pathom",
		"28": "Nakhon Phanom",
		"29": "Nakhon Ratchasima",
		"30": "Nakhon Sawan",
		"31": "Nakhon Si Thammarat",
		"32": "Nan",
		"33": "Narathiwat",
		"34": "Nong Bua Lamphu",
		"35": "Nong Khai",
		"36": "Nonthaburi",
		"37": "Pathum Thani",
		"38": "Pattani",
		"39": "Phangnga",
		"40": "Phatthalung",
		"41": "Phayao",
		"42": "Phetchabun",
		"43": "Phetchaburi",
		"44": "Phichit",
		"45": "Phitsanulok",
		"46": "Phra Nakhon Si Ayut.",
		"47": "Phrae",
		"48": "Phuket",
		"49": "Prachin Buri",
		"50": "Prachuap Khiri Khan",
		"51": "Ranong",
		"52": "Ratchaburi",
		"53": "Rayong",
		"54": "Roi Et",
		"55": "Sa Kaeo",
		"56": "Sakon Nakhon",
		"57": "Samut Prakan",
		"58": "Samut Sakhon",
		"59": "Samut Songkhram",
		"60": "Saraburi",
		"61": "Satun",
		"62": "Si Sa Ket",
		"63": "Sing Buri",
		"64": "Songkhla",
		"65": "Sukhothai",
		"66": "Supahn Buri",
		"67": "Surat Thani",
		"68": "Surin",
		"69": "Tak",
		"70": "Trang",
		"71": "Trat",
		"72": "Ubon Ratchathani",
		"73": "Udon Thani",
		"74": "Uttaradit",
		"75": "Yala",
		"76": "Yasothon",
		"77": "Uthai Thani",
		"78": "Bangkok",
		"C":  "Central",
		"E":  "East",
		"N":  "North",
		"S":  "South",
		"W":  "West",
	},
	"TL": {
		"AL": "Aileu",
		"AN": "Ainaro",
		"BA": "Baucau",
		"BO": "Bobonaro",
		"CO": "Cova Lima",
		"DI": "Dili",
		"ER": "Ermera",
		"LA": "Lautem",
		"LI": "Liquica",
		"MF": "Manufahi",
		"MT": "Manatuto",
		"OE": "OecussiI",
		"TL": "Timor-Leste",
		"VI": "Viqueque",
	},
	"TR": {
		"01": "Adana",
		"02": "Adiyaman",
		"03": "Afyon",
		"04": "Agri",
		"05": "Amasya",
		"06": "Ankara",
		"07": "Antalya",
		"08": "Artvin",
		"09": "Aydin",
		"10": "Balikesir",
		"11": "Bilecik",
		"12": "Bingöl",
		"13": "Bitlis",
		"14": "Bolu",
		"15": "Burdur",
		"16": "Bursa",
		"17": "Canakkale",
		"18": "Cankiri",
		"19": "Corum",
		"20": "Denizli",
		"21": "Diyarbakir",
		"22": "Edirne",
		"23": "Elazig",
		"24": "Erzincan",
		"25": "Erzurum",
		"26": "Eskisehir",
		"27": "Gaziantep",
		"28": "Giresun",
		"29": "Gümüshane",
		"30": "Hakkari",
		"31": "Hatay",
		"32": "Isparta",
		"33": "Icel",
		"34": "Istanbul",
		"35": "Izmir",
		"36": "Kars",
		"37": "Kastamonu",
		"38": "Kayseri",
		"39": "Kirklareli",
		"40": "Kirshehir",
		"41": "Kocaeli",
		"42": "Konya",
		"43": "Kütahya",
		"44": "Malatya",
		"45": "Manisa",
		"46": "K.Marash",
		"47": "Mardin",
		"48": "Mugla",
		"49": "Mush",
		"50": "Nevshehir",
		"51": "Nigde",
		"52": "Ordu",
		"53": "Rize",
		"54": "Sakarya",
		"55": "Samsun",
		"56": "Siirt",
		"57": "Sinop",
		"58": "Sivas",
		"59": "Tekirdag",
		"60": "Tokat",
		"61": "Trabzon",
		"62": "Tunceli",
		"63": "Shanliurfa",
		"64": "Ushak",
		"65": "Van",
		"66": "Yozgat",
		"67": "Zonguldak",
		"68": "Aksaray",
		"69": "Bayburt",
		"70": "Karaman",
		"71": "Kirikkale",
		"72": "Batman",
		"73": "Shirnak",
		"74": "Bartin",
		"75": "Ardahan",
		"76": "Igdir",
		"77": "Yalova",
	},
	"TW": {
		"01":  "Changhua",
		"02":  "Chiayi",
		"03":  "Chinmen",
		"04":  "Hsinchu",
		"05":  "Hualien",
		"06":  "Ilan",
		"07":  "Miaoli",
		"08":  "Nantou",
		"09":  "Penghu",
		"10":  "Pingtung",
		"11":  "Taichung",
		"12":  "Tainan",
		"13":  "Taitung",
		"14":  "Taoyuan",
		"15":  "Yunlin",
		"16":  "Keelung",
		"FJN": "Fu-chien",
		"KSH": "Kao-hsiung",
		"TPE": "Taipei",
		"TWN": "Taiwan",
	},
	"UA": {
		"CHG":     "Chernigivs&#39;ka",
		"CHR":     "Cherkas&#39;ka",
		"CHV":     "Chernovits&#39;ka",
		"DNP":     "Dnipropetrovs&#39;ka",
		"DON":     "Donets&#39;ka",
		"HAR":     "Harkivs&#39;ka",
		"HML":     "Hmel&#39;nits&#39;ka",
		"HRS":     "Hersons&#39;ka",
		"IVF":     "Ivano-Frankivs&#39;ka",
		"KIE":     "Kievs&#39;ka",
		"KIR":     "Kirovograds&#39;ka",
		"KRM":     "Respublika Krim",
		"L&#39;V": "L&#39;vivsbka",
		"LUG":     "Lugans&#39;ka",
		"MIK":     "Mikolaivs&#39;ka",
		"M_K":     "m.Kiev",
		"M_S":     "m.Sevastopil&#39;",
		"ODS":     "Odes&#39;ka",
		"POL":     "Poltavs&#39;ka",
		"RIV":     "Rivnens&#39;ka",
		"SUM":     "Sums&#39;ka",
		"TER":     "Ternopil&#39;s&#39;ka",
		"VIN":     "Vinnits&#39;ka",
		"VOL":     "Volins&#39;ka",
		"ZAK":     "Zakarpats&#39;ka",
		"ZAP":     "Zaporiz&#39;ka",
		"ZHI":     "Zhitomirs&#39;ka",
	},
	"US": {
		"AA": "Armed Forces America",
		"AE": "Armed Forces Europe",
		"AK": "Alaska",
		"AL": "Alabama",
		"AP": "Armed Forces Pacific",
		"AR": "Arkansas",
		"AS": "American Samoa",
		"AZ": "Arizona",
		"CA": "California",
		"CO": "Colorado",
		"CT": "Connecticut",
		"DC": "District of Columbia",
		"DE": "Delaware",
		"FL": "Florida",
		"GA": "Georgia",
		"GU": "Guam",
		"HI": "Hawaii",
		"IA": "Iowa",
		"ID": "Idaho",
		"IL": "Illinois",
		"IN": "Indiana",
		"KS": "Kansas",
		"KY": "Kentucky",
		"LA": "Louisiana",
		"MA": "Massachusetts",
		"MD": "Maryland",
		"ME": "Maine",
		"MI": "Michigan",
		"MN": "Minnesota",
		"MO": "Missouri",
		"MP": "Northern Mariana Isl",
		"MS": "Mississippi",
		"MT": "Montana",
		"NC": "North Carolina",
		"ND": "North Dakota",
		"NE": "Nebraska",
		"NH": "New Hampshire",
		"NJ": "New Jersey",
		"NM": "New Mexico",
		"NV": "Nevada",
		"NY": "New York",
		"OH": "Ohio",
		"OK": "Oklahoma",
		"OR": "Oregon",
		"PA": "Pennsylvania",
		"PR": "Puerto Rico",
		"RI": "Rhode Island",
		"SC": "South Carolina",
		"SD": "South Dakota",
		"TN": "Tennessee",
		"TX": "Texas",
		"UT": "Utah",
		"VA": "Virginia",
		"VI": "Virgin Islands",
		"VT": "Vermont",
		"WA": "Washington",
		"WI": "Wisconsin",
		"WV": "West Virginia",
		"WY": "Wyoming",
	},
	"UY": {
		"01": "Artigas",
		"02": "Canelones",
		"03": "Cerro Largo",
		"04": "Colonia",
		"05": "Duranzo",
		"06": "Flores",
		"07": "Florida",
		"08": "Lavalleja",
		"09": "Maldonado",
		"10": "Montevideo",
		"11": "Paysandu",
		"12": "Rio Negro",
		"13": "Rivera",
		"14": "Rocha",
		"15": "Salto",
		"16": "San Jose",
		"17": "Soriano",
		"18": "Tacuarembo",
		"19": "Treinta Y Tres",
	},
	"VE": {
		"AMA": "Amazon",
		"ANZ": "Anzoategui",
		"APU": "Apure",
		"ARA": "Aragua",
		"BAR": "Barinas",
		"BOL": "Bolivar",
		"CA":  "CARACAS",
		"CAR": "Carabobo",
		"COJ": "Cojedes",
		"DA":  "Delta Amacuro",
		"DF":  "Distrito Federal",
		"FAL": "Falcon",
		"GUA": "Guarico",
		"LAR": "Lara",
		"MER": "Merida",
		"MIR": "Miranda",
		"MON": "Monagas",
		"NE":  "Nueva Esparta",
		"POR": "Portuguesa",
		"SUC": "Sucre",
		"TAC": "Tachira",
		"TRU": "Trujillo",
		"VAR": "Vargas",
		"YAR": "Yaracuy",
		"ZUL": "Zulia",
	},
	"VN": {
		"65": "Ho Chi Minh, Thanh P",
	},
	"ZA": {
		"BRY": "Bryanston",
		"EC":  "Eastern Cape",
		"FS":  "Freestate",
		"GP":  "Gauteng",
		"KZN": "Kwazulu/Natal",
		"MP":  "Mpumalanga",
		"NC":  "Northern Cape",
		"NP":  "Northern Province",
		"NW":  "North-West",
		"WC":  "Western Cape",
	},
}

func StatesToMarkdown() string {
	res := ""
	for _, code := range CountriesCodes {
		res += StateToMarkdown(code) + "\n"
	}
	return res
}

func StateToMarkdown(countryCode string) string {
	res := fmt.Sprintf("\n# %s: %s\n\n", countryCode, Countries[countryCode])
	res += "Code | State name\n" +
		":---:|:------------\n"

	keys := make([]string, 0)
	for key, _ := range States[countryCode] {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	if len(keys) == 0 {
		res += "N/A  | -\n"
	} else {
		for _, key := range keys {
			res += fmt.Sprintf("%-5v| %s\n", key, States[countryCode][key])
		}
	}

	return res
}
